### PR TITLE
improvements (WORKFLOWS, README)

### PR DESCRIPTION
**Pull request by slimreaper35**
Simplify GitHub workflows:
- use only one file
- similar to the iterations pipeline
- lint, build, test

### CODE REVIEW

**Comment by czFIRE** [comment]
I think we should run the format, build, and test on all the pull requests. Imagine a situation in which someone creates a branch on a branch, and then there would be no check on the pull request.

I would also separate the clippy and build+test into two separate stages (so it's a bit clearer if it fails, then where was the problem)

**Comment by MatV404** [comment]
I would also like to second czFIRE. It might be worth to run the format, build, and test on all pull requests, just so we are sure that code that is being merged to any branch is correct and passes defined tests and thus likely won't break anything.

**Comment by slimreaper35** [comment]
I cannot imagine a use case where somebody would create a pull request to a branch other than _main_. Of course, you can merge someone else's branch locally or cherry-pick the commits, but that is a different story. Also, building and running tests take less than 1 second, so I do not see the point of over-engineering CI. The workflow is mostly copied from PV281 and the official Github Workflows Template repository.

**Comment by MatV404** [comment]
> I cannot imagine a use case where somebody would create a pull request to a branch other than _main_. Of course, you can merge someone else's branch locally or cherry-pick the commits, but that is a different story. Also, building and running tests take less than 1 second, so I do not see the point of over-engineering CI. The workflow is mostly copied from PV281 and the official Github Workflows Template repository.

Is it really going to be over-engineering?
According to [this](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet), you would only change one line in the code.
But, do as you see fit. I think it would be better to be safe than sorry, you never know what situation may arise during development. 
Let me know how you've decided, and if you still want to keep tests only on merges to main, I'll approve it.

**Comment by czFIRE** [comment]
I still stand behind my decision to include all the branches for just in case things.
I can easily imagine someone doing something on top of someone other job and then wanting to merge it back to their branch. 

This is just having more features and being more safe, what's the problem anyway?

 But in case there are any problems arising from incorrect merges into other branches, then we know whom to "thank".

**Comment by slimreaper35** [comment]
Fixed, I guess I'm in the minority

**Pull request merged**
